name: ${project.name}
version: ${project.version}
author: Sttot
# 插件的主类，记得带包名
main: 'city.newnan.newnanplus.NewNanPlusPlugin'
depend: ['Vault'] # 'ProtocolLib', 'BKCommonLib', 'PlaceholderAPI'
website: 'https://gk0wk.github.io/'
api-version: '1.14'
# 插件的命令（没有可以不写）
commands:
  # 命令名称，不带'/'
  nnp:
    # 命令描述，/help 时可以查看
    description: ''
    # 命令在控制台中的使用方式，带'/'
    usage: ''
  'nnp fly':
    description: '用它飞起来或者取消飞行模式，记得着落再取消'
    usage: 'nnp fly'
  'nnp save':
    description: '保存配置'
    usage: 'nnp save'
  'nnp reload':
    description: '重新载入配置'
    usage: 'nnp reload'
  'nnp allow':
    description: '允许某玩家正式进入游戏(获得玩家权限)'
    usage: 'nnp allow [PlayerID]'
  'nnp ctp':
    description: '允许某玩家正式进入游戏(获得玩家权限)'
    usage: 'nnp ctp [PlayerID]'
  'nnp cnew':
    description: '允许某玩家正式进入游戏(获得玩家权限)'
    usage: 'nnp cnew [PlayerID] x1 z1 x2 z2'